//! Synthetic `/etc/services` mount.
//!
//! Like `/etc/resolv.conf`, carrick injects `/etc/services` into the guest: under
//! `--fs host` the guest FS is a scratch (no /etc/services), so glibc's
//! `getservbyname`/`getservbyport` (and Go's port lookups, cgo `lookupPort`,
//! `net.parsePort`) fail with "unknown port". macOS ships a real `/etc/services`
//! in the SAME format as Linux, so we serve the host's file verbatim (with a
//! minimal built-in fallback). A single-file mount: it shadows only this exact
//! path; the rest of /etc comes from the rootfs.

use super::{EntryKind, Metadata, OpenContext, OpenFlags, Vfs, VfsError, VfsHandle};
use crate::linux_abi::{LINUX_EACCES, LINUX_ENOENT};

pub(crate) const ETC_SERVICES_PATH: &str = "/etc/services";

pub struct EtcServicesVfs {
    contents: Vec<u8>,
}

impl EtcServicesVfs {
    pub fn new() -> Self {
        Self {
            contents: synthesize_etc_services(),
        }
    }
}

impl Default for EtcServicesVfs {
    fn default() -> Self {
        Self::new()
    }
}

impl Vfs for EtcServicesVfs {
    fn lookup(&self, path: &str) -> Result<Metadata, VfsError> {
        if path == ETC_SERVICES_PATH {
            return Ok(Metadata {
                kind: EntryKind::File,
                mode: 0o644,
                size: self.contents.len() as u64,
                uid: 0,
                gid: 0,
                mtime_secs: 0,
                mtime_nanos: 0,
            });
        }
        Err(LINUX_ENOENT)
    }

    fn read_file(&self, path: &str) -> Result<Vec<u8>, VfsError> {
        if path == ETC_SERVICES_PATH {
            Ok(self.contents.clone())
        } else {
            Err(LINUX_ENOENT)
        }
    }

    fn open(
        &self,
        path: &str,
        flags: OpenFlags,
        _ctx: &OpenContext<'_>,
    ) -> Result<VfsHandle, VfsError> {
        if path != ETC_SERVICES_PATH {
            return Err(LINUX_ENOENT);
        }
        if flags.write {
            return Err(LINUX_EACCES);
        }
        Ok(VfsHandle::Bytes {
            path: path.to_string(),
            contents: self.contents.clone(),
            status_flags: 0,
        })
    }

    /// A guest may replace or delete its own /etc/services (e.g. an image
    /// builder unpacking a base image's copy): a mutation detaches this
    /// injection so the path falls through to the writable overlay.
    fn overridable(&self) -> bool {
        true
    }

    fn name(&self) -> &'static str {
        "etc_services"
    }
}

/// The macOS host's `/etc/services` (format-identical to Linux), or a minimal
/// built-in covering the well-known ports if the host file is unreadable.
fn synthesize_etc_services() -> Vec<u8> {
    if let Ok(host) = std::fs::read("/etc/services")
        && !host.is_empty()
    {
        return host;
    }
    b"# Generated by carrick (host /etc/services unavailable).\n\
      ftp\t21/tcp\n\
      ssh\t22/tcp\n\
      telnet\t23/tcp\n\
      smtp\t25/tcp\tmail\n\
      domain\t53/tcp\n\
      domain\t53/udp\n\
      http\t80/tcp\twww\n\
      https\t443/tcp\n\
      "
    .to_vec()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn serves_etc_services_with_smtp() {
        let v = EtcServicesVfs::new();
        let bytes = v.read_file(ETC_SERVICES_PATH).unwrap();
        assert!(!bytes.is_empty());
        assert!(String::from_utf8_lossy(&bytes).contains("smtp"));
        assert_eq!(v.read_file("/etc/hosts"), Err(LINUX_ENOENT));
    }

    #[test]
    fn etc_services_is_overridable() {
        // It is an injected default the guest may replace (kaniko unlinks it to
        // lay down the base image's copy), so it must report overridable.
        assert!(EtcServicesVfs::new().overridable());
    }
}
