//! Synthetic `/etc/resolv.conf` mount.
//!
//! Like `docker run`, carrick injects a working resolv.conf into every guest so
//! DNS resolves out of the box (the `--net host` contract). macOS does not hand
//! a Linux guest a usable one: `/etc/resolv.conf` there is a configd-managed
//! file behind a `/etc -> /private/etc` + `resolv.conf -> /var/run/resolv.conf`
//! symlink chain that `--fs host` does not resolve (the guest just gets ENOENT,
//! and Go/glibc then fall back to `[::1]:53` and fail). The real resolvers live
//! in the SystemConfiguration DNS store.
//!
//! carrick (the host process) CAN follow that chain, so it reads the host's
//! effective resolver config — which configd renders into `/etc/resolv.conf`,
//! falling back to `scutil --dns` for the primary scoped resolver — and serves
//! a clean copy here. The guest's resolver then gets real nameservers; the DNS
//! queries egress through the existing host-socket passthrough (the
//! `dispatch::net` syscall handlers), exactly as `docker run --net host` would.
//!
//! The config is snapshotted once at guest setup (like Docker, which writes the
//! container's resolv.conf at create time); a host DNS change mid-run is not
//! reflected, which matches container semantics.

use super::{EntryKind, Metadata, OpenContext, OpenFlags, Vfs, VfsError, VfsHandle};
use crate::linux_abi::{LINUX_EACCES, LINUX_ENOENT};

pub(crate) const RESOLV_CONF_PATH: &str = "/etc/resolv.conf";

pub struct ResolvConfVfs {
    contents: Vec<u8>,
}

impl ResolvConfVfs {
    pub fn new() -> Self {
        Self {
            contents: synthesize_resolv_conf(),
        }
    }
}

impl Default for ResolvConfVfs {
    fn default() -> Self {
        Self::new()
    }
}

impl Vfs for ResolvConfVfs {
    fn lookup(&self, path: &str) -> Result<Metadata, VfsError> {
        if path == RESOLV_CONF_PATH {
            return Ok(Metadata {
                kind: EntryKind::File,
                mode: 0o644,
                size: self.contents.len() as u64,
                uid: 0,
                gid: 0,
                mtime_secs: 0,
                mtime_nanos: 0,
            });
        }
        Err(LINUX_ENOENT)
    }

    fn read_file(&self, path: &str) -> Result<Vec<u8>, VfsError> {
        if path == RESOLV_CONF_PATH {
            Ok(self.contents.clone())
        } else {
            Err(LINUX_ENOENT)
        }
    }

    fn open(
        &self,
        path: &str,
        flags: OpenFlags,
        _ctx: &OpenContext<'_>,
    ) -> Result<VfsHandle, VfsError> {
        if path != RESOLV_CONF_PATH {
            return Err(LINUX_ENOENT);
        }
        if flags.write {
            return Err(LINUX_EACCES);
        }
        Ok(VfsHandle::Bytes {
            path: path.to_string(),
            contents: self.contents.clone(),
            status_flags: 0,
        })
    }

    /// A guest commonly rewrites /etc/resolv.conf: a mutation detaches this
    /// injection so the path falls through to the writable overlay (the guest's
    /// version wins; a delete makes it gone until recreated).
    fn overridable(&self) -> bool {
        true
    }

    fn name(&self) -> &'static str {
        "resolvconf"
    }
}

/// Build the guest resolv.conf from the macOS host's DNS configuration. Reads
/// the host `/etc/resolv.conf` (configd's render of the primary resolver, which
/// carrick — unlike the guest — can follow the symlink chain to), keeping only
/// the resolver directives; if that yields no `nameserver`, falls back to
/// `scutil --dns`. Always returns a syntactically valid file.
fn synthesize_resolv_conf() -> Vec<u8> {
    let mut out = String::from("# Generated by carrick from the macOS host DNS configuration.\n");
    let mut have_ns = false;

    if let Ok(host) = std::fs::read_to_string("/etc/resolv.conf") {
        for line in host.lines() {
            let t = line.trim();
            if is_resolver_directive(t) {
                out.push_str(t);
                out.push('\n');
                have_ns |= t.starts_with("nameserver");
            }
        }
    }

    if !have_ns {
        for ns in scutil_primary_nameservers() {
            out.push_str("nameserver ");
            out.push_str(&ns);
            out.push('\n');
            have_ns = true;
        }
    }

    // Last resort: no host resolver at all. Leave a comment rather than a bogus
    // server — DNS genuinely can't work, and a wrong nameserver would only add
    // multi-second timeouts. (Matches the host having no usable DNS.)
    if !have_ns {
        out.push_str("# (no host nameserver found)\n");
    }

    out.into_bytes()
}

fn is_resolver_directive(line: &str) -> bool {
    ["nameserver", "search", "domain", "options", "sortlist"]
        .iter()
        .any(|d| line.starts_with(d) && line[d.len()..].starts_with(char::is_whitespace))
}

/// Parse `scutil --dns` for the FIRST resolver scope's nameservers (the primary
/// resolver). Best-effort: returns empty on any failure.
fn scutil_primary_nameservers() -> Vec<String> {
    let Ok(output) = std::process::Command::new("/usr/sbin/scutil")
        .arg("--dns")
        .output()
    else {
        return Vec::new();
    };
    if !output.status.success() {
        return Vec::new();
    }
    let text = String::from_utf8_lossy(&output.stdout);
    let mut servers = Vec::new();
    let mut in_first_resolver = false;
    for line in text.lines() {
        let t = line.trim();
        if t.starts_with("resolver #") {
            // Stop once we've collected the first resolver's servers.
            if in_first_resolver {
                break;
            }
            in_first_resolver = t == "resolver #1";
            continue;
        }
        if in_first_resolver
            && let Some(rest) = t.strip_prefix("nameserver[")
            && let Some((_, addr)) = rest.split_once(" : ")
        {
            servers.push(addr.trim().to_string());
        }
    }
    servers
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lookup_is_a_regular_file() {
        let v = ResolvConfVfs::new();
        let md = v.lookup(RESOLV_CONF_PATH).unwrap();
        assert_eq!(md.kind, EntryKind::File);
        assert_eq!(md.mode, 0o644);
    }

    #[test]
    fn lookup_other_path_is_enoent() {
        let v = ResolvConfVfs::new();
        assert_eq!(v.lookup("/etc/hosts"), Err(LINUX_ENOENT));
    }

    #[test]
    fn open_read_returns_bytes_open_write_is_eacces() {
        let v = ResolvConfVfs::new();
        let h = v
            .open(
                RESOLV_CONF_PATH,
                OpenFlags {
                    read: true,
                    ..Default::default()
                },
                &OpenContext::default(),
            )
            .unwrap();
        assert!(matches!(h, VfsHandle::Bytes { .. }));
        assert_eq!(
            v.open(
                RESOLV_CONF_PATH,
                OpenFlags {
                    write: true,
                    ..Default::default()
                },
                &OpenContext::default(),
            ),
            Err(LINUX_EACCES)
        );
    }

    #[test]
    fn content_is_valid_resolv_conf() {
        // On any host the synthesized file parses as resolv.conf: every
        // non-comment line is a known directive. (We can't assert a nameserver
        // exists — a CI host may have none — but the format must be clean.)
        let v = ResolvConfVfs::new();
        let text = String::from_utf8(v.contents.clone()).unwrap();
        for line in text.lines() {
            let t = line.trim();
            if t.is_empty() || t.starts_with('#') {
                continue;
            }
            assert!(
                is_resolver_directive(t),
                "unexpected resolv.conf line: {t:?}"
            );
        }
    }

    #[test]
    fn resolv_conf_is_overridable() {
        // It is an injected default the guest commonly rewrites, so it must
        // report overridable (a guest mutation detaches the injection).
        assert!(ResolvConfVfs::new().overridable());
    }

    #[test]
    fn directive_match_is_token_aligned() {
        assert!(is_resolver_directive("nameserver 1.2.3.4"));
        assert!(is_resolver_directive("search example.com"));
        // A word that merely starts with a directive name is not one.
        assert!(!is_resolver_directive("searchengine foo"));
        assert!(!is_resolver_directive("nameservers 1.2.3.4"));
    }
}
