[package]
name = "carrick-abi"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "carrick_abi"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
carrick-syscall-abi = { path = "../carrick-syscall-abi" }
bitflags.workspace = true
serde.workspace = true
zerocopy.workspace = true
