[package]
name = "carrick-guest-arch"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
carrick-abi = { path = "../carrick-abi" }
carrick-syscall-abi = { path = "../carrick-syscall-abi" }
zerocopy.workspace = true
