[package]
name = "carrick-personality-linux"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
carrick-core = { path = "../carrick-core" }
carrick-core-abi = { path = "../carrick-core-abi" }
carrick-guest-arch = { path = "../carrick-guest-arch" }

[lints]
workspace = true

[dev-dependencies]
carrick-x86 = { path = "../carrick-x86" }
carrick-el1 = { path = "../carrick-el1", features = ["host-test"] }
carrick-el1-abi = { path = "../carrick-el1-abi" }
