[package]
name = "carrick-bsd"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "carrick_bsd"
path = "src/lib.rs"

[lints]
workspace = true

[target.'cfg(any(target_os = "macos", target_os = "freebsd"))'.dependencies]
carrick-hal = { path = "../carrick-hal" }
carrick-abi = { path = "../carrick-abi" }
carrick-host = { path = "../carrick-host" }
libc.workspace = true
