[package]
name = "carrick-el1-abi"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
carrick-fd-core = { path = "../carrick-fd-core" }
carrick-pipe-core = { path = "../carrick-pipe-core" }
carrick-inotify-core = { path = "../carrick-inotify-core" }
carrick-mmu-core = { path = "../carrick-mmu-core" }
carrick-sched-core = { path = "../carrick-sched-core" }
