//! Render `docs/support-matrix.md` from the per-suite reports. Deterministic
//! (stable order, no timestamps) so the committed file diffs cleanly — a `git
//! diff` after a run IS the regression review. See design §9.

use crate::parsers::SuiteOutcome;
use crate::verdict::{SideSummary, SuiteReport, Verdict};

const ECOSYSTEMS: [(&str, &str); 4] = [
    ("cpython", "CPython"),
    ("go", "Go"),
    ("node", "Node.js / libuv"),
    ("ltp", "LTP"),
];

/// One side's headline cell: a `<passed>/<n>` fraction when there are per-test
/// counts, else the suite status word (§9).
fn cell(s: &SideSummary) -> String {
    // A truncated run reports FIRST, and keeps its partial counts visible. It
    // has real rows, so the `n > 0` branch below would render it as an ordinary
    // fraction and hide the fact that the inventory is incomplete.
    if s.result == SuiteOutcome::Truncated {
        return format!("TIMEOUT@{}/{}", s.totals.passed, s.totals.n);
    }
    if s.totals.n > 0 {
        format!("{}/{}", s.totals.passed, s.totals.n)
    } else {
        match s.result {
            SuiteOutcome::Success => "SUCCESS".to_string(),
            SuiteOutcome::Failure => "FAILURE".to_string(),
            SuiteOutcome::None => "CRASH".to_string(),
            SuiteOutcome::Empty => "EMPTY".to_string(),
            SuiteOutcome::Truncated => "TIMEOUT".to_string(),
        }
    }
}

pub fn render(reports: &[SuiteReport]) -> String {
    let mut out = String::new();
    out.push_str("# carrick support matrix\n\n");
    out.push_str(
        "Generated by `just conformance` / `just matrix` from \
         `scripts/conformance/suites.toml` — do not edit by hand. Each suite runs \
         under `carrick run` and `docker run` (the Linux oracle) with identical \
         trailing argv; `verdict` is the carrick-vs-oracle diff. `git diff` on this \
         file after a run is the regression review.\n\n",
    );
    out.push_str(
        "Verdicts: **MATCH** identical · **INCOMPLETE** closure run lacked an identical, nonempty all-pass result · **DIFF** diverges but every divergence is a \
         tracked/known or unchanged gap (green) · **REGRESSION** a new, unexcused \
         break (red, fails the gate) · **NEW** first observation, not yet baselined · \
         **CARRICK_CRASH**/**TIMEOUT** carrick aborted/hung · **BUDGET_KILL** cut off at \
         the harness's Carrick-only diagnostic budget while still progressing, below the \
         suite's declared timeout — non-gating, re-run serially to get its real verdict · \
         **ORACLE_FAIL** the Docker oracle broke (never counted against carrick).\n\n",
    );

    for (key, title) in ECOSYSTEMS {
        let rows: Vec<&SuiteReport> = reports.iter().filter(|r| r.ecosystem == key).collect();
        if rows.is_empty() {
            continue;
        }
        out.push_str(&format!("## {title}\n\n"));
        out.push_str(&headline(&rows));
        out.push_str("\n\n| Suite | tier | carrick | oracle | verdict | gaps |\n");
        out.push_str("|---|---|---|---|---|---|\n");
        for r in rows {
            let gaps = if r.new_diffs.is_empty() {
                format!("{}", r.known_diffs.len())
            } else {
                format!("{} known · {} NEW", r.known_diffs.len(), r.new_diffs.len())
            };
            out.push_str(&format!(
                "| `{}` | {} | {} | {} | {} | {} |\n",
                r.name,
                r.tier,
                cell(&r.carrick),
                cell(&r.docker),
                r.verdict.as_str(),
                gaps,
            ));
        }
        out.push('\n');
    }

    out.push_str(
        "---\n\nSee also: `crates/carrick-cli/tests/conformance.rs` (the deterministic, \
         line-exact ABI probe gate) and `.agents/skills/ltp-conformance/scripts/ltp-sweep.sh` \
         (full LTP discovery). This matrix is the coarse behavioral axis; the probe gate is \
         the precise one.\n",
    );
    out
}

/// Display order for the per-ecosystem verdict counts. `headline` FILTERS over
/// this array, so a verdict missing from it vanishes from the counts without any
/// error — `every_verdict_appears_in_the_headline_order` is the tripwire.
const HEADLINE_ORDER: [Verdict; 9] = [
    Verdict::Match,
    Verdict::Incomplete,
    Verdict::Diff,
    Verdict::New,
    Verdict::Regression,
    Verdict::CarrickCrash,
    Verdict::Timeout,
    Verdict::BudgetKill,
    Verdict::OracleFail,
];

fn headline(rows: &[&SuiteReport]) -> String {
    let mut counts: std::collections::BTreeMap<&str, usize> = std::collections::BTreeMap::new();
    for r in rows {
        *counts.entry(r.verdict.as_str()).or_default() += 1;
    }
    let parts: Vec<String> = HEADLINE_ORDER
        .iter()
        .filter_map(|v| {
            counts
                .get(v.as_str())
                .map(|n| format!("{n} {}", v.as_str()))
        })
        .collect();
    let noun = if rows.len() == 1 { "suite" } else { "suites" };
    format!("{} {noun} — {}", rows.len(), parts.join(" · "))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// `headline` counts verdicts by filtering over a hand-written order array.
    /// A verdict missing from it does not error — it silently VANISHES from the
    /// counts, so a matrix could read "10 suites — 10 MATCH" while hiding ten
    /// budget kills. The exhaustive `match` below is the tripwire: adding a
    /// `Verdict` variant breaks this test to compile until the variant is
    /// listed here AND present in `HEADLINE_ORDER`.
    #[test]
    fn every_verdict_appears_in_the_headline_order() {
        let all = [
            Verdict::Match,
            Verdict::Incomplete,
            Verdict::Diff,
            Verdict::Regression,
            Verdict::New,
            Verdict::CarrickCrash,
            Verdict::Timeout,
            Verdict::BudgetKill,
            Verdict::OracleFail,
        ];
        for verdict in all {
            match verdict {
                Verdict::Match
                | Verdict::Incomplete
                | Verdict::Diff
                | Verdict::Regression
                | Verdict::New
                | Verdict::CarrickCrash
                | Verdict::Timeout
                | Verdict::BudgetKill
                | Verdict::OracleFail => {}
            }
            assert!(
                HEADLINE_ORDER.contains(&verdict),
                "{} is missing from the matrix headline order and would vanish \
                 from the counts",
                verdict.as_str()
            );
        }
        assert_eq!(
            HEADLINE_ORDER.len(),
            all.len(),
            "the headline order must list each verdict exactly once"
        );
    }
}
