//! Render `docs/support-matrix.md` from the per-suite reports. Deterministic
//! (stable order, no timestamps) so the committed file diffs cleanly — a `git
//! diff` after a run IS the regression review. See design §9.

use crate::parsers::SuiteOutcome;
use crate::verdict::{SideSummary, SuiteReport, Verdict};

const ECOSYSTEMS: [(&str, &str); 4] = [
    ("cpython", "CPython"),
    ("go", "Go"),
    ("node", "Node.js / libuv"),
    ("ltp", "LTP"),
];

/// One side's headline cell: a `<passed>/<n>` fraction when there are per-test
/// counts, else the suite status word (§9).
fn cell(s: &SideSummary) -> String {
    if s.totals.n > 0 {
        format!("{}/{}", s.totals.passed, s.totals.n)
    } else {
        match s.result {
            SuiteOutcome::Success => "SUCCESS".to_string(),
            SuiteOutcome::Failure => "FAILURE".to_string(),
            SuiteOutcome::None => "CRASH".to_string(),
            SuiteOutcome::Empty => "EMPTY".to_string(),
        }
    }
}

pub fn render(reports: &[SuiteReport]) -> String {
    let mut out = String::new();
    out.push_str("# carrick support matrix\n\n");
    out.push_str(
        "Generated by `just conformance` / `just matrix` from \
         `scripts/conformance/suites.toml` — do not edit by hand. Each suite runs \
         under `carrick run` and `docker run` (the Linux oracle) with identical \
         trailing argv; `verdict` is the carrick-vs-oracle diff. `git diff` on this \
         file after a run is the regression review.\n\n",
    );
    out.push_str(
        "Verdicts: **MATCH** identical · **DIFF** diverges but every divergence is a \
         tracked/known or unchanged gap (green) · **REGRESSION** a new, unexcused \
         break (red, fails the gate) · **NEW** first observation, not yet baselined · \
         **CARRICK_CRASH**/**TIMEOUT** carrick aborted/hung · **ORACLE_FAIL** the \
         Docker oracle broke (never counted against carrick).\n\n",
    );

    for (key, title) in ECOSYSTEMS {
        let rows: Vec<&SuiteReport> = reports.iter().filter(|r| r.ecosystem == key).collect();
        if rows.is_empty() {
            continue;
        }
        out.push_str(&format!("## {title}\n\n"));
        out.push_str(&headline(&rows));
        out.push_str("\n\n| Suite | tier | carrick | oracle | verdict | gaps |\n");
        out.push_str("|---|---|---|---|---|---|\n");
        for r in rows {
            let gaps = if r.new_diffs.is_empty() {
                format!("{}", r.known_diffs.len())
            } else {
                format!("{} known · {} NEW", r.known_diffs.len(), r.new_diffs.len())
            };
            out.push_str(&format!(
                "| `{}` | {} | {} | {} | {} | {} |\n",
                r.name,
                r.tier,
                cell(&r.carrick),
                cell(&r.docker),
                r.verdict.as_str(),
                gaps,
            ));
        }
        out.push('\n');
    }

    out.push_str(
        "---\n\nSee also: `crates/carrick-cli/tests/conformance.rs` (the deterministic, \
         line-exact ABI probe gate) and `.claude/skills/ltp-conformance/scripts/ltp-sweep.sh` \
         (full LTP discovery). This matrix is the coarse behavioral axis; the probe gate is \
         the precise one.\n",
    );
    out
}

fn headline(rows: &[&SuiteReport]) -> String {
    let mut counts: std::collections::BTreeMap<&str, usize> = std::collections::BTreeMap::new();
    for r in rows {
        *counts.entry(r.verdict.as_str()).or_default() += 1;
    }
    let order = [
        Verdict::Match,
        Verdict::Diff,
        Verdict::New,
        Verdict::Regression,
        Verdict::CarrickCrash,
        Verdict::Timeout,
        Verdict::OracleFail,
    ];
    let parts: Vec<String> = order
        .iter()
        .filter_map(|v| {
            counts
                .get(v.as_str())
                .map(|n| format!("{n} {}", v.as_str()))
        })
        .collect();
    format!("{} suites — {}", rows.len(), parts.join(" · "))
}
