[package]
name = "carrick-native-darwin"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "carrick_native_darwin"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
carrick-dsr = { path = "../carrick-dsr" }
carrick-dsr-aarch64 = { path = "../carrick-dsr-aarch64" }
getrandom.workspace = true
libc.workspace = true
tempfile.workspace = true

[build-dependencies]
cc = "1"
