[package]
name = "carrick-core-abi"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
carrick-guest-arch = { path = "../carrick-guest-arch" }
carrick-mmu-core = { path = "../carrick-mmu-core" }
carrick-sched-core = { path = "../carrick-sched-core" }

[lints]
workspace = true
